format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

app:
  envs:
    - FORCE_COLOR: 1

trigger_map:
  - push_branch: '*'
    pipeline: test-on-Ubuntu-and-Xcode-stacks
pipelines:
  test-on-Ubuntu-and-Xcode-stacks:
    stages:
      - test-stacks: {}
stages:
  test-stacks:
    workflows:
      - test-on-Ubuntu-stack: {}
      - test-on-Xcode-stack: {}

meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard

workflows:
  test-on-Ubuntu-stack:
    steps:
      - script:
          title: Generate version name from timestamp
          inputs:
            - content: |-
                #!/bin/bash
                export APPLICATION_VERSION_NAME="$(date +%s%N)"
                echo "Generated version_name: $APPLICATION_VERSION_NAME"
                envman add --key APPLICATION_VERSION_NAME --value "$APPLICATION_VERSION_NAME"
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - path::./:
          title: Upload Android application
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - mobile_application_id: '7b54b434-59ea-4ef7-868b-12c9180842f7'
            - mobile_application_version_file_path: example-app.apk
            - version_name: '$APPLICATION_VERSION_NAME'
          outputs:
            - DATADOG_UPLOADED_APPLICATION_VERSION_ID: DATADOG_UPLOADED_APPLICATION_VERSION_ID
      - git::https://github.com/DataDog/synthetics-test-automation-bitrise-step-run-tests.git:
          title: Run Android tests
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - public_ids: 'rxd-vdv-qce'
            - mobile_application_version: $DATADOG_UPLOADED_APPLICATION_VERSION_ID
            - fail_on_critical_errors: true
      - path::./:
          title: Upload iOS application
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - mobile_application_id: 'bcb5d107-5536-4fe5-a4a8-ea34a6c9bbee'
            - mobile_application_version_file_path: example-app.ipa
            - version_name: '$APPLICATION_VERSION_NAME'
          outputs:
            - DATADOG_UPLOADED_APPLICATION_VERSION_ID: DATADOG_UPLOADED_APPLICATION_VERSION_ID
      - git::https://github.com/DataDog/synthetics-test-automation-bitrise-step-run-tests.git:
          title: Run iOS tests
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - public_ids: 'bcq-y54-rq7'
            - mobile_application_version: $DATADOG_UPLOADED_APPLICATION_VERSION_ID
            - fail_on_critical_errors: true

  test-on-Xcode-stack:
    meta:
      bitrise.io:
        stack: osx-xcode-edge
        machine_type_id: g2-m1.4core
    steps:
      - script:
          title: Generate version name from timestamp
          inputs:
            - content: |-
                #!/bin/bash
                export APPLICATION_VERSION_NAME="$(date +%s)"
                echo "Generated version_name: $APPLICATION_VERSION_NAME"
                envman add --key APPLICATION_VERSION_NAME --value "$APPLICATION_VERSION_NAME"
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - path::/Users/vagrant/git:
          title: Upload Android application
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - mobile_application_id: '7b54b434-59ea-4ef7-868b-12c9180842f7'
            - mobile_application_version_file_path: example-app.apk
            - version_name: '$APPLICATION_VERSION_NAME'
          outputs:
            - DATADOG_UPLOADED_APPLICATION_VERSION_ID: DATADOG_UPLOADED_APPLICATION_VERSION_ID
      - git::https://github.com/DataDog/synthetics-test-automation-bitrise-step-run-tests.git:
          title: Run Android tests
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - public_ids: 'rxd-vdv-qce'
            - mobile_application_version: $DATADOG_UPLOADED_APPLICATION_VERSION_ID
            - fail_on_critical_errors: true
      - path::/Users/vagrant/git:
          title: Upload iOS application
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - mobile_application_id: 'bcb5d107-5536-4fe5-a4a8-ea34a6c9bbee'
            - mobile_application_version_file_path: example-app.ipa
            - version_name: '$APPLICATION_VERSION_NAME'
          outputs:
            - DATADOG_UPLOADED_APPLICATION_VERSION_ID: DATADOG_UPLOADED_APPLICATION_VERSION_ID
      - git::https://github.com/DataDog/synthetics-test-automation-bitrise-step-run-tests.git:
          title: Run iOS tests
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - public_ids: 'bcq-y54-rq7'
            - mobile_application_version: $DATADOG_UPLOADED_APPLICATION_VERSION_ID
            - fail_on_critical_errors: true

  audit-this-step:
    steps:
      - script:
          inputs:
            - content: |-
                #!/bin/bash
                set -ex
                stepman audit --step-yml ./step.yml
