name: Run unit tests
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test
        run: bats ./tests
